site_name: Bytenami

site_url: https://bytenami.com/
site_author: Tyler Ryu
copyright: Copyright &copy; 2021 Tyler Ryu
site_description: Solve your data needs, no hassle, no delays

theme:
  name: null
  custom_dir: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

nav:
  - Home: index.md